[skypanel-leading-space]
enabled = true
port = http,https
filter = skypanel-leading-space
logpath = /var/log/nginx/access.log
          /var/log/apache2/access.log
          /var/log/skypanel/access.log
maxretry = 1
bantime = 604800
findtime = 86400
